create table if not exists b_docbrown_tinkoff (
   ID int(16) not null auto_increment,
   operationDate int(16) not null,
   operationId varchar(255) not null unique,
   accountNumber varchar(255) not null,
   bic varchar(16),
   typeOfOperation varchar(255) not null,
   category varchar(255),
   trxnPostDate varchar(16),
   authorizationDate int(255),
   drawDate int(16),
   chargeDate int(16),
   docDate int(16),
   payVo varchar(255),
   vo varchar(255),
   operationAmount int(16),
   operationCurrencyDigitalCode varchar(8),
   accountAmount int(16),
   accountCurrencyDigitalCode varchar(8),
   rubleAmount int(16),
   description varchar(255),
   payPurpose varchar(255),
   payer_acct varchar(32),
   payer_inn varchar(32),
   payer_kpp varchar(32),
   payer_name varchar(255),
   payer_bicRu varchar(16),
   payer_corAcct varchar(32),
   receiver_acct varchar(32),
   receiver_inn varchar(32),
   receiver_name varchar(255),
   receiver_bicRu varchar(32),
   receiver_corAcct varchar(32),
   counterParty_account varchar(32),
   counterParty_inn varchar(32),
   counterParty_kpp varchar(32),
   counterParty_name varchar(255),
   counterParty_bankName varchar(255),
   counterParty_bankBic varchar(32),
   counterParty_corrAccount varchar(32),
   cardNumber varchar(32),
   ucid int(16),
   mcc varchar(8),
   rrn varchar(16),
   CRM_ID varchar(255),
   PDF int(16),
   primary key (ID)
);